### ISSUE TITLE
using primary base key for both tables connection - handle conflict 

### ISSUE THREAD

**Issue by Elmeslmaney** [osalvador/ReplicaDB#136]
- Is conflict resolution between two tables during data synchronization or replication part of the project development plan?
- Does the project development plan account for resolving conflicts based on user-specified primary keys or unique identifiers?
- The conflict resolution mechanism should handle differences arising from additions, modifications, or deletions in the two tables.
- The user should be able to choose the primary keys or unique identifiers to be used for conflict resolution.

**Comment by Elmeslmaney** [comment]
@osalvador would you please support

**Comment by osalvador** [comment]
Hi @Elmeslmaney ,

- Is conflict resolution between two tables during data synchronization or replication part of the project development plan?
  + The incremental mode performs an UPSERT by primary key, so if the record exists in the target table it will be updated, otherwise inserted. [Incremental mode doc](https://osalvador.github.io/ReplicaDB/docs/docs.html#incremental)
- Does the project development plan account for resolving conflicts based on user-specified primary keys or unique identifiers?
  + Yes, in the incremental mode ReplicaDB obtains the primary keys of the sink table to perform the UPSERT. 
- The conflict resolution mechanism should handle differences arising from additions, modifications, or deletions in the two tables.
  + ReplicaDB cannot know which records have been deleted from the source table. For this you will need a CDC or some other triggers based strategy. 
- The user should be able to choose the primary keys or unique identifiers to be used for conflict resolution.
  + It could be interesting, but some database engines do not allow to execute MERGE or UPSERT statements if there is no primary key or unique index. 

The main objective of ReplicaDB is to perform data replication in the most efficient way possible, which is why we rely on the capabilities of each database engine to obtain the best possible performance. 

Thanks!
