### ISSUE TITLE
postgres sink - Invalid input syntax for type bytea

### ISSUE THREAD

**Issue by ScottChapman** [osalvador/ReplicaDB#147]
Syncing from MySQL -> postgres. Seeing the following error:
`2023-07-03 08:56:06,350 ERROR ReplicaTask:69 ERROR in TaskId-0 inserting data to sink table: [ERROR: invalid input syntax for type bytea`

**Comment by osalvador** [comment]
Hi @ScottChapman 

Please to open a new issue, follow the issue template: 

**Describe the bug**
A clear and concise description of what the bug is, with verbose log. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Source table DDL
2. Sink table DDL
3. ReplicaDB configuration `options-file`. 

**Expected behavior**
A clear and concise description of what you expected to happen.

**Additional context**
Add any other context about the problem here. Running environment (cloud, on premise, java version..), source and sink technologies (Oracle, MySQL, Postgres...)

**Comment by ScottChapman** [comment]
tracking with #148
