### ISSUE TITLE
Oracle to MSSQL Verbose - 0 rows processed

### ISSUE THREAD

**Issue by MichalisDBA** [osalvador/ReplicaDB#151]
**Describe the bug**
Hello.

I noticed when i use replicadb from source oracle to sink mssql, with verbose enabled, the message about the rows processed is always 0 although the replication works just fine.

It seems to be similar to an old bug, https://github.com/osalvador/ReplicaDB/issues/130.

From Oracle:
```
ReplicaTask:67 A total of 0 rows processed by task 0
```

**To Reproduce**
1. Source Oracle Table.
2. Sink MSSQL Table.

**Expected behavior**
The INFO message should show how many rows have been processed when the source is MSSQL

**Comment by osalvador** [comment]
Hi @MichalisDBA 

ReplicaDB uses the BulkCopy API to copy the data to SQL Server. The problem is that in this API there is no way to get the copied records. 

I could try other strategies, for example: https://learn.microsoft.com/en-us/sql/connect/jdbc/use-bulk-copy-api-batch-insert-operation?view=sql-server-ver16, but it will take me time to validate them. 

When the source is also SQL Server, the copied records are retrieved from the source resultset, so with source and sink SQL Server the counter works fine.

**Comment by MichalisDBA** [comment]
@osalvador Ok thank you for the info!
