### ISSUE TITLE
Comparison with exisiting data in INCREMENTAL mode 

### ISSUE THREAD

**Issue by ud20** [osalvador/ReplicaDB#6]
In incremental mode is there a comparison being done to see which rows already exist and updating only whats missing from source to sink? 
I am trying to understand the difference between complete and incremental modes. Incremental I thought is supposed to be for merging and updating whats missing. But what I see is we are actually truncating the data and then inserting everything again.

**Comment by osalvador** [comment]
Hi @ud20 

The incremental mode aims to replicate only the new data added in the source table to the sink table. This technique drastically reduces the amount of data that must be moved between both databases and becomes essential with large tables with billions of rows.

To do this, it is necessary to have a strategy for filtering the new data at the source. Usually a date type column or a unique incremental ID is used. Therefore it will be necessary to use the `source.where` parameter to retrieve only the newly added rows in the source table since the last time the replica was executed. 

Currently, you must store the last value of the column used to determine changes in the source table. In future versions, ReplicaDB will do this automatically. 

In incremental mode, ReplicaDB needs to create a staging table where data is copied in parallel. The last step of the replication is to merge the staging table with the sink table. 

The `TRUNCATE` instruction is only perform on the staging table and not on the sink table.
